version: '3.8'

networks:
  monitoring:
    driver: bridge

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_USERS_ALLOW_SIGN_UP: "false"
    networks:
      - monitoring
    restart: unless-stopped

  react-app:
    build: ./react-app
    container_name: react-app
    ports:
      - "3002:3000"
    environment:
      - REACT_APP_GRAFANA_URL=http://localhost:3001
    depends_on:
      - grafana
    networks:
      - monitoring

volumes:
  grafana_data: